[profile.default]
solc_version = "0.8.25"
evm_version = "cancun"
src = "src"
out = "out"
script = "script"
libs = ["node_modules"]
fs_permissions = [{ access = "read", path = "out-optimized" }, { access = "read-write", path = "gas_calculations" }]
allow_paths = ["*", "/"]
ignored_warnings_from = ["node_modules", "src/integrations"]
gas_limit = "18446744073709551615"
memory_limit = 2147483648
verbosity = 3

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}" 
testnet = "${TESTNET_RPC_URL}" 

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
